# Configuration file for Grype vulnerability scanner

# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  # Add any specific vulnerabilities to ignore below
  # Example:
  # - vulnerability: "GHSA-3xgq-45jj-v275"
  #   package:
  #     name: "cross-spawn"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false 