# Configuration file for Grype vulnerability scanner

# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  # Ignore specific CVEs - once Dockerfile docker image with fixes are available, these should be removed from the ignore list
  - vulnerability: CVE-2025-9086
  
  - vulnerability: CVE-2025-10148
  
  - vulnerability: CVE-2025-8177
  
  - vulnerability: CVE-2025-8176
  
  - vulnerability: CVE-2025-8851
  
  - vulnerability: CVE-2023-52356
  
  - vulnerability: CVE-2023-6277
  
  - vulnerability: CVE-2023-6228

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
