reject: [
  # TODO: Incompatibility issues found with the TTK backend if we update socket.io client
  "socket.io-client",
  # TODO: Upgrading react may cause many implications
  "react",
  "react-ace",
  "react-dom",
  "react-keyed-file-browser",
  "react-router-dom",
  "react-scripts",
  "web-vitals",
  "@types/react",
  "@testing-library/jest-dom",
  "@testing-library/react",
  "@testing-library/user-event",
  # Keeping the bootstrap to the same version because there are many renames in the class names in the recent versions
  "bootstrap"

]
