## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  # TODO: Tried to upgrade the react and getting many issues while building the app due to the difference in the libraries.
  # So keeping the react versions same for now.
  "react",
  "react-ace",
  "react-dom",
  "react-router-dom",
  "react-scripts",
  "web-vitals",
  "@types/react",
  "react-markdown",
  "@testing-library/jest-dom",
  "@testing-library/react",
  "@testing-library/user-event",
  # Keeping the bootstrap to the same version because there are many renames in the class names in the recent versions
  "bootstrap",
  # TODO: Mermaid is throwing an error while building if upgraded. Need to investigate the root cause.
  "mermaid",
  # antd v5+ currently suffers from poor performance https://github.com/ant-design/ant-design/issues/39746
  "antd",
  ## TODO: The new version of npm-check-updates uses new Glob v9.x and it is introducing a dependency Package "path-scurry@1.6.1" which is licensed under "BlueOak-1.0.0" which is not permitted by the Mojaloop License Policy
  "npm-check-updates",
]
