version: "3.7"

services:
  mojaloop-testing-toolkit-ui:
    image: mojaloop-testing-toolkit-ui:local
    build:
      context: .
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
      # - PAYEE_SIM_BRAND_ICON=some_image
    command:
      - sh
      - /usr/share/nginx/start.sh
